### ISSUE TITLE
bwa index issue while annotating

### ISSUE THREAD

**Issue by Koen-vdl** [WGLab/NanoMod#14]
Hi,

I run into the same error when annotating fast5 files with NanoMod: 

```
[E::bwa_idx_load_from_disk] fail to locate the index files
Process Process-14:
Traceback (most recent call last):
  File "/home/kvandelannoo/miniconda3/envs/nanomod_env/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/kvandelannoo/miniconda3/envs/nanomod_env/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kvandelannoo/NanoMod/bin/scripts/myRefBaseSignalAnnotation.py", line 1353, in correctAndAnnotate_handler
    correctAndAnnotate(moptions_dc, f5files)
  File "/home/kvandelannoo/NanoMod/bin/scripts/myRefBaseSignalAnnotation.py", line 348, in correctAndAnnotate
    print ('Fatal Error!!! returncode is non-zero(%d) for "%s"' % (returncode, curcmd))
NameError: global name 'curcmd' is not defined
```

It looks to me like no bwa index is written. This error keeps reoccurring multiple times while processing fast5 reads. 

I compared fast5 files before and after NanoMod annotation using h5dump and I can confirm no information is added to the files. 

I tested different versions of Albacore to no avail (the ones's still available are 2.3.0, 2.3.1, 2.3.2, 2.3.3 2.3.4).

Could you advise how I can troubleshoot?

Kind regards.

KV

**Comment by liuqianhn** [comment]
Hi @Koen-vdl , this is because your reference genome is not indexed. Please use bwa to index your reference genome or use `--alignStr minimap2` to use minimap2 for alignment. By default, the alignment tools is `bwa mem`.

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
