### ISSUE TITLE
there is no package called ‘cowplot’

### ISSUE THREAD

**Issue by loafyyy** [WGLab/NanoMod#21]
I am running into the following error when using NanoMod:
```
/home/pengj1/.local/share/r-miniconda/envs/py27nanomod/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in loadNamespace(name) : there is no package called ‘cowplot’

  warnings.warn(x, RRuntimeWarning)
Number of files in /mnt/isilon/wang_lab/jackie/project/long-read_tutorial/samples/meth1/NB01/is 16249
Start sorting
SaveTest 1
Finish SaveTest
Test data is saved in mRes//mod_sign_test.txt
Traceback (most recent call last):
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/NanoMod.py", line 468, in <module>
    args.func(args);
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/NanoMod.py", line 178, in mDetect
    myDetect.mDetect(moptions)
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/scripts/myDetect.py", line 643, in mDetect
    mboxplot(moptions)
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/scripts/myDetect.py", line 264, in mboxplot
    importr('cowplot')
  File "/home/pengj1/.local/share/r-miniconda/envs/py27nanomod/lib/python2.7/site-packages/rpy2/robjects/packages.py", line 453, in importr
    env = _get_namespace(rname)
rpy2.rinterface.RRuntimeError: Error in loadNamespace(name) : there is no package called ‘cowplot’
```
I created the conda environment using `conda env create -f env.py27nanomod.yml`, however, it seems like the cowplot package is required to use NanoMod but it is missing. 

I tried installing cowplot using `conda install -c r r-cowplot`, however, I still get the error below (even when I also do `conda install -c r r-stringr r-stringi`):
```
/home/pengj1/.local/share/r-miniconda/envs/py27nanmod_manual/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error: package or namespace load failed for ‘stringr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/pengj1/.local/share/r-miniconda/envs/py27nanmod_manual/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory

  warnings.warn(x, RRuntimeWarning)
/home/pengj1/.local/share/r-miniconda/envs/py27nanmod_manual/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/pengj1/.local/share/r-miniconda/envs/py27nanmod_manual/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory

  warnings.warn(x, RRuntimeWarning)
Number of files in /mnt/isilon/wang_lab/jackie/project/long-read_tutorial/samples/meth1/NB01/is 16249
Start sorting
SaveTest 1
Finish SaveTest
Test data is saved in mRes//mod_sign_test.txt
Traceback (most recent call last):
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/NanoMod.py", line 468, in <module>
    args.func(args);
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/NanoMod.py", line 178, in mDetect
    myDetect.mDetect(moptions)
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/scripts/myDetect.py", line 643, in mDetect
    mboxplot(moptions)
  File "/mnt/isilon/wang_lab/jackie/project/long-read_tutorial/NanoMod/bin/scripts/myDetect.py", line 265, in mboxplot
    importr('stringr')
  File "/home/pengj1/.local/share/r-miniconda/envs/py27nanmod_manual/lib/python2.7/site-packages/rpy2/robjects/packages.py", line 453, in importr
    env = _get_namespace(rname)
rpy2.rinterface.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/pengj1/.local/share/r-miniconda/envs/py27nanmod_manual/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
```

Could you please help me with this error? Thanks!

**Comment by loafyyy** [comment]
This error can be fixed with `conda install -c r r-cowplot`. Thanks @agouru55! The package should be included in the conda environment .yml file.

**Comment by liuqianhn** [comment]
@loafyyy Thanks, Jackie. Please update it since it has not be updated for years.

**Comment by loafyyy** [comment]
@liuqianhn I made a [pull request](https://github.com/WGLab/NanoMod/pull/22) with the commands I used to manually set up the conda environment. Could you take a look at it and approve it if it's acceptable? Thanks!
